# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from dataclasses import dataclass, field
from typing import Any

import aie.utils as aie_utils
import torch

from iron.common import (
    AIERuntimeArgSpec,
    DesignGenerator,
    MLIROperator,
    PythonGeneratedMLIRArtifact,
)
from iron.common.device_utils import get_kernel_dir
from iron.common.sequence import OperatorSequence
from iron.common.stream.ops import GEMM, SOFTMAX

BYTES_PER_ELEMENT = 2  # every buffer in a fused sequence is addressed as bfloat16


@dataclass
class _MHAStreamGroup(MLIROperator):
    """One stream-dse design, used as an ``OperatorSequence`` child.

    ``k`` is how many fused groups the attention core is split into and
    ``group_index`` which of them this is, in the order
    :data:`~iron.operators.mha_prefill_stream.stream_design.GROUP_LAYERS` lists them.
    """

    seq_len: int
    d_head: int
    k: int
    group_index: int
    context: Any = field(default=None, repr=False, compare=False)

    def __post_init__(self):
        MLIROperator.__init__(self, context=self.context)

    @property
    def _design(self):
        from iron.operators.mha_prefill_stream import stream_design

        return stream_design

    def _dims(self):
        return {
            "k": self.k,
            "seq_len": self.seq_len,
            "d_head": self.d_head,
            "npu": aie_utils.get_current_device().resolve().name,
        }

    def get_mlir_artifact(self):
        return PythonGeneratedMLIRArtifact(
            f"{self.name}.mlir",
            DesignGenerator(
                self.operator_dir / "stream_design.py",
                "load_group",
                (self.group_index,),
                self._dims(),
            ),
        )

    def get_kernel_artifacts(self):
        design = self._design
        tiles = design.kernel_tiles(self.seq_len, self.d_head, self.k)
        per_layer = {
            design.SCORES_NODE: (GEMM, tiles[design.SCORES_NODE]),
            design.CONTEXT_NODE: (GEMM, tiles[design.CONTEXT_NODE]),
            design.SOFTMAX_NODE: (SOFTMAX, None),
        }
        layers = design.GROUP_LAYERS[self.k][self.group_index]
        base_dir, kernel_dir = self.context.base_dir, get_kernel_dir()
        return [
            artifact
            for kernel, tile in dict.fromkeys(per_layer[layer] for layer in layers)
            for artifact in kernel.kernel_artifacts(
                base_dir, kernel_dir, **(dict(zip("mkn", tile)) if tile else {})
            )
        ]

    def reference(self, *inputs):
        """CPU result for this group, for the reference and compare dispatches.

        One layer per group, which is what :data:`GROUP_LAYERS` gives for
        ``k = LAYER_BY_LAYER``.
        """
        design = self._design
        (layer,) = design.GROUP_LAYERS[self.k][self.group_index]
        if layer == design.SOFTMAX_NODE:
            return torch.softmax(inputs[0].float(), dim=-1).to(inputs[0].dtype)
        return inputs[0] @ inputs[1]

    def design_key(self):
        """Groups whose generated design is byte-identical share it."""
        return self._design.group_digest(self.group_index, **self._dims())

    def get_arg_spec(self):
        """The group's runtime arguments, shaped by the exported graph."""
        shapes = self._design.workload_for(self.seq_len, self.d_head).shapes
        inputs, outputs = self._design.group_ports(self.seq_len, self.d_head, self.k)[
            self.group_index
        ]
        return [AIERuntimeArgSpec("in", shapes[name]) for name in inputs] + [
            AIERuntimeArgSpec("out", shapes[name]) for name in outputs
        ]


class MHAPrefillStream(OperatorSequence):
    """Prefill attention core generated by stream-dse and deployed as one full ELF.

    One head's ``softmax(q @ k_t) @ v``, replayed over ``heads`` by slicing the
    per-head buffers, since only the query dimension is splittable across cores and a
    single head therefore occupies a single column. The projections around the core
    stay on IRON's own GEMM.

    Each group is deployed as its own xclbin rather than fused into one ELF: the
    softmax's input is distributed straight from a shim tile to each of its cores, and
    fusing the groups puts more of those transfers on one shim than it has DMA
    channels.

    The caller hands in a ``q`` already scaled by ``1/sqrt(d_head)`` and a ``k_t``
    already transposed; see
    :mod:`~iron.operators.mha_prefill_stream.reference`. Runtime buffers are named by
    that module: ``q``, ``k_t``, ``v``, ``output``. Building requires ``stream-dse``
    (``pip install stream-dse`` + ``stream-setup-aie``); importing does not.
    """

    def __init__(
        self,
        seq_len,
        d_head,
        heads=1,
        k=None,
        context=None,
        share_designs=True,
        dispatch="separate",
    ):
        from iron.operators.mha_prefill_stream.stream_design import (
            LAYER_BY_LAYER,
            group_ports,
            trace_size,
        )

        k = LAYER_BY_LAYER if k is None else k
        ports = [
            inputs + outputs for inputs, outputs in group_ports(seq_len, d_head, k)
        ]
        groups = [
            _MHAStreamGroup(
                seq_len=seq_len,
                d_head=d_head,
                k=k,
                group_index=index,
                context=context,
            )
            for index in range(len(ports))
        ]
        head_bytes = seq_len * d_head * BYTES_PER_ELEMENT
        per_head = ("q", "k_t", "v", "output")
        runlist = []
        for head in range(heads):
            window = f"[{head * head_bytes}:{(head + 1) * head_bytes}]"
            for group, names in zip(groups, ports):
                runlist.append(
                    (group, *(n + window if n in per_head else n for n in names))
                )
        super().__init__(
            name=f"mha_prefill_stream_k{k}_h{heads}_s{seq_len}_d{d_head}",
            runlist=runlist,
            input_args=["q", "k_t", "v"],
            output_args=["output"],
            buffer_sizes={name: heads * head_bytes for name in per_head},
            trace_size=trace_size(),
            share_designs=share_designs,
            dispatch=dispatch,
            context=context,
        )
