#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import time

import pytest
import torch

# The design is generated by stream-dse at compile() time. stream-dse is an optional
# dependency (see requirements_stream.txt) absent from the default CI image, so skip
# this whole module when it is unavailable.
pytest.importorskip(
    "stream", reason="stream-dse not installed (see requirements_stream.txt)"
)

from iron.common.test_utils import verify_buffer
from iron.operators.mha_prefill_stream.op import MHAPrefillStream
from iron.operators.mha_prefill_stream.reference import (
    CONTEXT,
    KEY_TRANSPOSED,
    QUERY,
    VALUE,
    generate_golden_reference,
)

# Key and value stay whole on a memory tile, which bounds the sequence length.
SEQ_LEN, D_HEAD = 256, 64

HEADS = [1, 2]

# Fused groups to deploy the core as: one design, or one per layer.
FUSION_GROUPS = [1, 3]

# Sequence lengths the blocked-key design is checked at, with the heads it replays the
# design over: one query block per core, and two, which is what puts a query loop around
# the key loop. Several heads accumulate over a longer running scale and land closer to
# the tolerance than one does, so the margin is watched at two as well.
FLASH_CASES = [(SEQ_LEN, 1), (2 * SEQ_LEN, 1), (SEQ_LEN, 2)]

# Timed dispatches per test; the reported latency is the fastest of them.
TIMED_RUNS = 3


def _staged(operator, golden_ref):
    run = operator.get_callable()
    for name in (QUERY, KEY_TRANSPOSED, VALUE):
        buffer = run.get_buffer(name)
        buffer.torch_view()[:] = golden_ref[name].to(torch.bfloat16).flatten()
        buffer.to("npu")
    return run


@pytest.mark.supported_devices("npu2")
@pytest.mark.metrics(
    Latency=r"Latency \(us\): (?P<value>[\d\.]+)",
    Bandwidth=r"Effective Bandwidth: (?P<value>[\d\.e\+-]+) GB/s",
)
@pytest.mark.parametrize("causal", [False, True])
@pytest.mark.parametrize("k", FUSION_GROUPS)
@pytest.mark.parametrize("heads", HEADS)
def test_mha_prefill_stream(heads, k, causal, aie_context):
    golden_ref = generate_golden_reference(SEQ_LEN, D_HEAD, heads=heads, causal=causal)
    operator = MHAPrefillStream(
        seq_len=SEQ_LEN,
        d_head=D_HEAD,
        heads=heads,
        k=k,
        causal=causal,
        context=aie_context,
    )
    operator.compile()

    run = _staged(operator, golden_ref)
    run()
    output = run.get_buffer("output").to_torch().reshape((heads, SEQ_LEN, D_HEAD))
    # The bar iron/operators/mha meets for the same computation.
    errors = verify_buffer(
        output, "output", golden_ref[CONTEXT], rel_tol=4e-2, abs_tol=1.5e-1
    )
    assert not errors, f"Test failed with errors: {errors}"

    # The first dispatch on a callable pays for its hardware context, so time the
    # ones after it.
    latencies = []
    for _ in range(TIMED_RUNS):
        start = time.perf_counter()
        run()
        latencies.append((time.perf_counter() - start) * 1e6)
    elapsed_us = min(latencies)
    total_bytes = 4 * heads * SEQ_LEN * D_HEAD  # bf16 q in + context out
    print(f"Latency (us): {elapsed_us:.2f}")
    print(f"Effective Bandwidth: {total_bytes / (elapsed_us * 1e-6) / 1e9:.4f} GB/s")


@pytest.mark.supported_devices("npu2")
@pytest.mark.parametrize("seq_len, heads", FLASH_CASES)
def test_mha_prefill_stream_flash(seq_len, heads, aie_context):
    """Blocking the key is what lifts the sequence length, so this runs past what the
    resident-key design can reach. Masking is inside the kernels, so it is always causal.
    """
    golden_ref = generate_golden_reference(seq_len, D_HEAD, heads=heads, causal=True)
    operator = MHAPrefillStream(
        seq_len=seq_len, d_head=D_HEAD, heads=heads, flash=True, context=aie_context
    )
    operator.compile()

    run = _staged(operator, golden_ref)
    run()
    output = run.get_buffer("output").to_torch().reshape((heads, seq_len, D_HEAD))
    errors = verify_buffer(
        output, "output", golden_ref[CONTEXT], rel_tol=4e-2, abs_tol=1.5e-1
    )
    assert not errors, f"Test failed with errors: {errors}"
