# SPDX-FileCopyrightText: Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from dataclasses import dataclass, field
from typing import Any

import aie.utils as aie_utils

from iron.common import (
    MLIROperator,
    AIERuntimeArgSpec,
    KernelObjectArtifact,
    SourceArtifact,
    PythonGeneratedMLIRArtifact,
    DesignGenerator,
)
from iron.common.device_utils import get_kernel_dir


@dataclass
class SwiGLUPrefillStream(MLIROperator):
    """Fused SwiGLU-prefill block whose MLIR is generated by stream-dse.

    Unlike the composite ``SwiGLUPrefill`` (which chains four separately compiled
    sub-operators and orchestrates them from the host), this operator compiles a
    single fused MLIR design produced by stream-dse: one xclbin with a single
    runtime sequence taking ``(input, weights_1, weights_2, weights_3, output)``.

    The MLIR is produced lazily at compile time by ``stream_design.py``, which
    calls the installed ``stream-dse`` package. Building therefore requires
    ``stream-dse`` (``pip install stream-dse`` + ``stream-setup-aie``); merely
    importing this operator does not.
    """

    seq_len: int
    embedding_dim: int
    hidden_dim: int
    seq_len_tile_size: int = 32
    embedding_tile_size: int = 32
    hidden_tile_size: int = 64
    last_gemm_down: bool = True
    in_dtype: str = field(default="bf16", repr=False)
    out_dtype: str = field(default="bf16", repr=False)
    trace_size: int = field(default=0, repr=False)
    rows: int = field(default=4, repr=False)
    num_aie_columns: int = field(default=8, repr=False)
    backend: str = field(default="ortools_gscip", repr=False)
    # Weights are runtime data supplied by the caller after construction; they
    # are not needed to build the design.
    weights_1: Any = field(default=None, repr=False, compare=False)
    weights_2: Any = field(default=None, repr=False, compare=False)
    weights_3: Any = field(default=None, repr=False, compare=False)
    context: Any = field(default=None, repr=False, compare=False)

    def __post_init__(self):
        MLIROperator.__init__(self, context=self.context)

    def get_mlir_artifact(self):
        npu = aie_utils.get_current_device().resolve().name
        return PythonGeneratedMLIRArtifact(
            f"{self.name}.mlir",
            DesignGenerator(
                self.operator_dir / "stream_design.py",
                "run_main_aie_codegen_swiglu",
                (),
                {
                    "seq_len": self.seq_len,
                    "embedding_dim": self.embedding_dim,
                    "hidden_dim": self.hidden_dim,
                    "in_dtype": self.in_dtype,
                    "out_dtype": self.out_dtype,
                    "trace_size": self.trace_size,
                    "rows": self.rows,
                    "cols": self.num_aie_columns,
                    "npu": npu,
                    "seq_len_tile_size": self.seq_len_tile_size,
                    "embedding_tile_size": self.embedding_tile_size,
                    "hidden_tile_size": self.hidden_tile_size,
                    "last_gemm_down": self.last_gemm_down,
                    "backend": self.backend,
                },
            ),
        )

    def _mm_kernel(self, tile_m, tile_k, tile_n):
        """Compile the shared ``mm.cc`` kernel for one tile configuration.

        stream-dse emits dimension-suffixed kernel symbols (e.g.
        ``matmul_bf16_bf16_32_32_64``) so the gate/up and down GEMMs -- which use
        different tile shapes -- can coexist in one fused design. Upstream
        ``mm.cc`` emits unsuffixed ``matmul_bf16_bf16`` / ``zero_bf16``, so we
        rename them to match the names the generated MLIR calls.
        """
        base_dir = self.context.base_dir
        kernel_dir = get_kernel_dir()
        suffix = f"{tile_m}_{tile_k}_{tile_n}"
        return KernelObjectArtifact(
            f"mm_{suffix}.o",
            dependencies=[
                SourceArtifact(base_dir / "aie_kernels" / kernel_dir / "mm.cc")
            ],
            extra_flags=[
                f"-DDIM_M={tile_m}",
                f"-DDIM_K={tile_k}",
                f"-DDIM_N={tile_n}",
                "-Dbf16_bf16_ONLY",
            ],
            rename_symbols={
                "matmul_bf16_bf16": f"matmul_bf16_bf16_{suffix}",
                "zero_bf16": f"zero_bf16_{suffix}",
            },
        )

    def get_kernel_artifacts(self):
        base_dir = self.context.base_dir
        kernel_dir = get_kernel_dir()
        kernels = [
            # gate/up projections: input (seq, embedding) @ W (embedding, hidden)
            self._mm_kernel(
                self.seq_len_tile_size,
                self.embedding_tile_size,
                self.hidden_tile_size,
            ),
            KernelObjectArtifact(
                "silu.o",
                dependencies=[
                    SourceArtifact(base_dir / "aie_kernels" / kernel_dir / "silu.cc")
                ],
            ),
            KernelObjectArtifact(
                "mul.o",
                dependencies=[
                    SourceArtifact(base_dir / "aie_kernels" / "generic" / "mul.cc")
                ],
            ),
        ]
        if self.last_gemm_down:
            # down projection: intermediate (seq, hidden) @ W (hidden, embedding)
            kernels.insert(
                1,
                self._mm_kernel(
                    self.seq_len_tile_size,
                    self.hidden_tile_size,
                    self.embedding_tile_size,
                ),
            )
        return kernels

    def set_up_artifacts(self):
        # stream-dse emits a placed/routed design that links a distinct kernel
        # object per core, so it needs --dynamic-objFifos (both targets) and
        # --no-unified (separate per-core compilation; xclbin only).
        xclbin_artifact, insts_artifact = self.get_artifacts(dynamic_obj_fifos=True)
        xclbin_artifact.extra_flags.append("--no-unified")
        self.xclbin_artifact = xclbin_artifact
        self.insts_artifact = insts_artifact
        self.add_artifacts([xclbin_artifact, insts_artifact])

    def get_arg_spec(self):
        specs = [
            AIERuntimeArgSpec("in", (self.seq_len, self.embedding_dim)),  # input
            AIERuntimeArgSpec("in", (self.embedding_dim, self.hidden_dim)),  # weights_1 (gate)
            AIERuntimeArgSpec("in", (self.embedding_dim, self.hidden_dim)),  # weights_2 (up)
        ]
        if self.last_gemm_down:
            specs.append(
                AIERuntimeArgSpec("in", (self.hidden_dim, self.embedding_dim))
            )  # weights_3 (down)
            specs.append(AIERuntimeArgSpec("out", (self.seq_len, self.embedding_dim)))
        else:
            specs.append(AIERuntimeArgSpec("out", (self.seq_len, self.hidden_dim)))
        return specs
